<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5c5f065cde15c66084b3133b1fadde1c
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PEAR' => 
            array (
                0 => __DIR__ . '/..' . '/pear/pear_exception',
            ),
        ),
        'M' => 
        array (
            'Mail' => 
            array (
                0 => __DIR__ . '/..' . '/pear/mail',
            ),
        ),
        'C' => 
        array (
            'Console' => 
            array (
                0 => __DIR__ . '/..' . '/pear/console_getopt',
            ),
        ),
    );

    public static $fallbackDirsPsr0 = array (
        0 => __DIR__ . '/..' . '/pear/pear-core-minimal/src',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5c5f065cde15c66084b3133b1fadde1c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5c5f065cde15c66084b3133b1fadde1c::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit5c5f065cde15c66084b3133b1fadde1c::$prefixesPsr0;
            $loader->fallbackDirsPsr0 = ComposerStaticInit5c5f065cde15c66084b3133b1fadde1c::$fallbackDirsPsr0;

        }, null, ClassLoader::class);
    }
}
